edcgeared/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectMultipleField, SubmitField
from wtforms.validators import InputRequired, DataRequired
from flask_wtf.file import FileField, FileAllowed

class PostForm(FlaskForm):
    """Post form"""

    title = StringField('Title', validators=[InputRequired()])
    content = TextAreaField('Content', validators=[InputRequired()])
    categories = SelectMultipleField('Categories', coerce=int, choices=[], default=['1'], validators=[DataRequired()])
    image = FileField('Update post image', validators=[FileAllowed(['jpg', 'png'])])

    submit = SubmitField('Post')

edcgeared/main/routes.py
from flask import Blueprint, render_template, request
from edcgeared.models import Post, Category

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/news")
def index():
    """Index"""

    page = request.args.get('page', 1, type=int)
    query = request.args.get('q')

    if query:
        posts = Post.query.filter(Post.title.contains(query) | 
        Post.content.contains(query)).paginate(page=page, per_page=5)
    else:
        posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)

    return render_template("index.html", posts=posts)


@main.route("/reviews")
def reviews():
    """Reviews"""
    
    categories = Category.query.filter(Category.title == "Reviews")

    page = request.args.get('page', 1, type=int)
    posts = Post.query.join(Post.categories).filter(Category.title.in_(category.title for category in categories)).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)

    return render_template("index.html", posts=posts)


@main.route("/bestgear")
def bestgear():
    """Best gear"""

    categories = Category.query.filter(Category.title == "Best gear")

    page = request.args.get('page', 1, type=int)
    posts = Post.query.join(Post.categories).filter(Category.title.in_(category.title for category in categories)).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)

    return render_template("index.html", posts=posts)

edcgeared/posts/routes.py
import os
from flask import jsonify, render_template, url_for, flash, redirect, request, abort, Blueprint, current_app
from flask_login import login_required, current_user
from flask_restful import Api, Resource
from edcgeared.models import Category, Post
from edcgeared.posts.forms import PostForm
from edcgeared import db
from edcgeared.posts.utils import save_post_image

posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    """Create new post"""

    form = PostForm()

    form.categories.choices = [(category.id, category.title) for category in Category.query.all()]

    if form.validate_on_submit():
        image_file = "default.jpg"

        if form.image.data:
            image_file = save_post_image(form.image.data)

        slug = form.title.data.replace(" ", "-").lower()
        post = Post(title=form.title.data, content=form.content.data, author=current_user, slug=slug, image=image_file)
        categories = db.session.query(Category).filter(Category.id.in_((form.categories.data))).all()
        post.categories = [category for category in categories]

        db.session.add(post)
        db.session.commit()

        return redirect(url_for('main.index'))

    return render_template("create_post.html", title="New post", form=form,
                            legend="New post")


@posts.route("/post/<string:slug>")
def post(slug):
    """Read post"""

    post = Post.query.filter_by(slug=slug).first_or_404()

    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/update/<string:slug>", methods=['GET', 'POST'])
@login_required
def update_post(slug):
    """Update post"""

    post = Post.query.filter_by(slug=slug).first_or_404()

    if post.author != current_user:
        abort(403)

    form = PostForm()

    form.categories.choices = [(category.id, category.title) for category in Category.query.all()]

    if form.validate_on_submit():
        if form.image.data:
            image_file = save_post_image(form.image.data)
            if post.image != "default.jpg":
                os.remove(current_app.root_path + '/static/post_images/' + post.image)
            post.image = image_file

        post.title = form.title.data
        post.content = form.content.data
        post.slug = form.title.data.replace(" ", "-").lower()

        categories = db.session.query(Category).filter(Category.id.in_((form.categories.data))).all()
        post.categories = [category for category in categories]

        db.session.commit()

        flash("Post updated!", "success")
        return redirect(url_for('posts.post', slug=post.slug))

    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
        form.categories.data = [category.id for category in post.categories]

    return render_template('create_post.html', title="Update post",
                            form=form, legend="Update post")


@posts.route("/post/delete/<string:slug>", methods=['POST'])
@login_required
def delete_post(slug):
    """Delete post"""

    post = Post.query.filter_by(slug=slug).first_or_404()

    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()

    flash("Post deleted!", 'success')
    return redirect(url_for('main.index'))

@posts.route("/post/rate/<string:slug>", methods=['PUT'])
def rate_post(slug):
    """Rate a post"""

    post = Post.query.filter_by(slug=slug).first_or_404()

    if "rating" in request.json:
        if request.json['rating'] == 'like':
            post.rating += 1
        elif request.json['rating'] == 'dislike':
            post.rating -= 1
        else:
            return "Invalid request data", 400
    else:
        return "Invalid request data", 400
    
    db.session.commit()

    return jsonify(post.rating)

edcgeared/users/routes.py
import os

from flask import render_template, url_for, flash, redirect, request, Blueprint, current_app
from flask_login import login_user, current_user, logout_user, login_required
from edcgeared import db, bcrypt
from edcgeared.users.forms import RegistrationForm, LoginForm, UpdateProfileForm
from edcgeared.models import User, Post
from edcgeared.users.utils import save_profile_image

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    """Registration"""

    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegistrationForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(first_name=form.first_name.data, last_name=form.last_name.data,
        email=form.email.data, password=hashed_password)

        db.session.add(user)
        db.session.commit()

        flash('Account created successfully!', 'success')
        return redirect(url_for('users.login'))

    return render_template("register.html", title="Sign up", form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    """Log in"""

    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
 
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash('You have logged in.', 'success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('Incorrect email or password!', 'danger')
            return render_template("login.html", title="Sign in", form=form)

    elif request.method == "GET":
        return render_template("login.html", title="Sign in", form=form)  


@users.route("/settings", methods=['GET', 'POST'])
@login_required
def settings():
    """User account settings"""

    form = UpdateProfileForm()

    if form.validate_on_submit():
        if form.image.data:
            image_file = save_profile_image(form.image.data)
            if current_user.image_file != "default.jpg":
                os.remove(current_app.root_path + '/static/profile_images/' + current_user.image_file)
            current_user.image_file = image_file
 
        current_user.email = form.email.data
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data

        db.session.commit()

        flash('Profile updated!', 'success')
        return redirect(url_for('users.settings'))

    elif request.method == "GET":
        form.email.data = current_user.email
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name

    image_file = url_for("static", filename='profile_images/' + current_user.image_file)

    return render_template("settings.html", title="User settings", 
    image_file=image_file,
    form=form)


@users.route("/logout")
@login_required
def logout():
    """Log out"""

    logout_user()
    return redirect(url_for('main.index'))


@users.route("/user/<string:email>")
def user_posts(email):
    """User posts"""

    user = User.query.filter_by(email=email).first_or_404()
    page = request.args.get('page', 1, type=int)

    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)

    return render_template("user_posts.html", posts=posts, user=user)

edcgeared/templates/create_post.html
{% extends "layout.html" %} {% block content %}
<div
  class="container content-section d-flex justify-content-center row row-cols-2"
>
  <form method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-3 text-center">{{ legend }}</legend>
      <div class="form-group mb-3">
        {{ form.title.label(class="form-control-label") }} {% if
        form.title.errors %} {{ form.title(class="form-control is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.title.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>
        {% else %} {{form.title(class="form-control")}} {% endif %}
      </div>
      <div class="form-group mb-2">
        {{ form.content.label(class="form-control-label")}}{% if
        form.content.errors %} {{ form.content(class="form-control is-invalid")
        }}
        <div class="invalid-feedback">
          {%for error in form.content.errors%}
          <span>{{error}}</span>
          {% endfor %}
        </div>
        {% else %} {{form.content(class="form-control")}} {% endif %}
      </div>
      <div class="form-group mb-2">
        {{ form.categories.label(class="form-control-label")}}{% if
        form.categories.errors %} {{ form.categories(class="form-control
        is-invalid") }}
        <div class="invalid-feedback">
          {%for error in form.categories.errors%}
          <span>{{error}}</span>
          {% endfor %}
        </div>
        {% else %} {{form.categories(class="form-control")}} {% endif %}
      </div>
      <div class="form-group mb-2">
        <label> {{ form.image.label() }} </label> <br />
        {{ form.image(class="form-control-file") }} {% if form.image.errors %}
        {% for error in form.image.errors %}
        <span class="text-danger"> {{ error }} </span>
        {% endfor %} {% endif %}
      </div>
    </fieldset>
    <div class="form-group pb-3 pt-3 d-flex justify-content-center">
      {{ form.submit(class="btn btn-outline-info")}}
    </div>
  </form>
</div>

{% endblock content %}

edcgeared/templates/index.html
{% extends "layout.html" %} {% block content %}
<body>
  {% if posts.items %} {% for post in posts.items %}
  <article class="media content-section article-preview">
    <div class="article-metadata">
      <img
        class="rounded-circle article-author-img"
        src="{{ url_for('static', filename='profile_images/' + post.author.image_file) }}"
      />
      <a
        class="mr-2 article-author"
        href="{{ url_for('users.user_posts', email=post.author.email) }}"
        >{{ post.author.first_name }} {{post.author.last_name }}</a
      >
    </div>
    <div class="media-body">
      <h4>
        <a
          class="article-title"
          href="{{ url_for('posts.post', slug=post.slug) }}"
          >{{ post.title }}</a
        >
      </h4>
      <div class="media container">
        <img
          class="article-img"
          src="{{ url_for('static', filename='post_images/' + post.image) }}"
        />
      </div>
    </div>
    <div class="article-footer">
      <small class="text-muted"
        >{{ post.date_posted.strftime('%Y-%m-%d') }}</small
      >
      <small class="text-muted post-likes">Likes: {{ post.rating }}</small>
    </div>
  </article>
  {% endfor %}
  <div>
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1,
    left_current=1, right_current=2) %} {% if page_num %} {% if posts.page ==
    page_num %}
    <a
      class="btn btn-info mb-2"
      href="{{ url_for('main.index', page=page_num) }}"
      >{{ page_num }}</a
    >
    {% else %}
    <a
      class="btn btn-outline-info mb-2"
      href="{{ url_for('main.index', page=page_num) }}"
      >{{ page_num }}</a
    >
    {% endif %} {% else %} ... {% endif %} {% endfor %}
  </div>
  {% else %}
  <div>
    <article class="media content-section">
      <h4>No posts found</h4s>
    </article>
  </div>
  {%endif%}
</body>
{% endblock content %}

edcgeared/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />

    <link
      href="{{ url_for('static', filename='style.css')}}"
      rel="stylesheet"
      type="text/css"
    />

    <link rel="stylesheet" href="https://formden.com/static/cdn/font-awesome/4.4.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    {% if title %}
    <title>{{ title }} | EDC Geared</title>
    {% else %}
    <title>EDC Geared</title>
    {% endif %}
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{ url_for('main.index') }}"
            >EDC Geared</a
          >
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto ms-1 mb-3 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ url_for('main.index') }}">News</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.reviews') }}">Reviews</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.bestgear') }}">Best Gear</a>
              </li>
            </ul>
            <ul class="nav navbar-nav me-3 mb-3 mb-lg-0">
                {% if current_user.is_authenticated %}
                <li>
                  <a class="nav-link" :link href="{{ url_for('posts.new_post') }}"><span class="" aria-hidden="true"></span>
                    <i class="fa fa-solid fa-plus">
                  </i></a>
                </li>
                <li>
                  <a class="nav-link" :link href="{{ url_for('users.settings') }}"><span class="" aria-hidden="true"></span>
                    <i class="fa fa-user fa-lg fa-user-logged-in">
                  </i></a>
                  {% else %}
                  <a class="nav-link" :link href="{{ url_for('users.login') }}"><span class="" aria-hidden="true"></span>
                    <i class="fa fa-user fa-lg">
                    </i></a>
                      {% endif %}
                </li>
            </ul>
            <form class="d-flex justify-content-center">
              <input
                class="form-control me-2"
                type="search"
                placeholder="Search"
                aria-label="Search"
                name="q"
              />
              <button class="btn btn-outline-light" type="submit">
                Search
              </button>
            </form>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
      {% with messages = get_flashed_messages(with_categories=true) %} 
      {% if messages %} 
      {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
      {% endfor %} {% endif %} {% endwith %} 
      {% block content %}{% endblock %}
      </div>

      <div class="footer-basic">
        <footer>
            <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
            <ul class="list-inline">
                <!-- <li class="list-inline-item"><a href="{{ url_for('main.index') }}">Home</a></li> -->
                <li class="list-inline-item"><a href="#">Services</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <p class="copyright">EDC Geared © 2022</p>
        </footer>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

edcgeared/templates/login.html
{% extends "layout.html" %} {% block content %}
<div
  class="container content-section d-flex justify-content-center row row-cols-2"
>
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-3 text-center">Log in</legend>
      <div class="form-group mb-3">
        {{ form.email.label(class="form-control-label") }} {% if
        form.email.errors %} {{ form.email(class="form-control is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>
        {% else %} {{form.email(class="form-control")}} {% endif %}
      </div>
      <div class="form-group mb-2">
        {{ form.password.label(class="form-control-label")}}{% if
        form.password.errors %} {{ form.password(class="form-control
        is-invalid") }}
        <div class="invalid-feedback">
          {%for error in form.password.errors%}
          <span>{{error}}</span>
          {% endfor %}
        </div>
        {% else %} {{form.password(class="form-control")}} {% endif %}
        <small class="text-muted text-center">
          <a href="#">Forgot password?</a>
        </small>
      </div>
      <div class="form-check pt-2">
        {{ form.remember(class="form-check-input")}} {{
        form.remember.label(class="form-check-label")}}
      </div>
    </fieldset>
    <div class="form-group pb-3 pt-3 d-flex justify-content-center">
      {{ form.submit(class="btn btn-outline-info")}}
    </div>
  </form>
</div>
<div class="container border-top pt-2 text-center">
  <small class="text-muted">
    Don't have an account?
    <a class="ml-2" href="{{ url_for('users.register') }}">Sign up!</a>
  </small>
</div>
{% endblock content %}

edcgeared/templates/post.html
{% extends "layout.html" %} {% block content %}
<body>
  <article class="media content-section">
    <div class="article-metadata">
      <img
        class="rounded-circle article-author-img"
        src="{{ url_for('static', filename='profile_images/' + post.author.image_file) }}"
      />
      <a
        class="article-author"
        href="{{ url_for('users.user_posts', email=post.author.email) }}"
        >{{ post.author.first_name }} {{post.author.last_name }}</a
      >
      <small class="text-muted" style="float: right"
        >{{ post.date_posted.strftime('%Y-%m-%d') }}</small
      >
    </div>

    <div class="media-body">
      {% if post.author == current_user %}
      <div style="float: right">
        <a
          class="btn btn-outline-warning btn-sm mt-1 mb-1"
          href="{{ url_for('posts.update_post', slug=post.slug) }}"
          >Update</a
        >
        <button
          type="button"
          class="btn btn-outline-danger btn-sm m-1"
          data-toggle="modal"
          data-target="#deleteModal"
        >
          Delete
        </button>
      </div>
      {% endif %}
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
    <div>
      <footer class="article-footer">
        <small class="text-muted post-likes">{{ post.rating }} likes </small>
      </footer>
    </div>
  </article>
  <!-- Modal -->
  <div
    class="modal fade"
    id="deleteModal"
    tabindex="-1"
    role="dialog"
    aria-labelledby="deleteModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete post?</h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            Close
          </button>
          <form
            action="{{ url_for('posts.delete_post', slug=post.slug) }}"
            method="POST"
          >
            <input class="btn btn-danger" type="submit" value="Delete" />
          </form>
        </div>
      </div>
    </div>
  </div>
</body>
{% endblock content %}

edcgeared/templates/settings.html
{% extends "layout.html" %} {% block content %}
<body>
  <div class="content-section">
    <legend class="container text-bold mb-3">
      Edit profile
      <span class="">
        <a
          class="btn btn-outline-danger logout-btn"
          href="{{ url_for('users.logout') }}"
          role="button"
          >Sign out</a
        >
      </span>
    </legend>
    <div class="media container">
      <img class="rounded-circle account-img" src="{{ image_file }}" />
    </div>
    <div class="container d-flex justify-content-right row row-cols-2">
      <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
          <div class="form-group mb-3">
            {{ form.email.label(class="form-control-label") }} {% if
            form.email.errors %} {{ form.email(class="form-control is-invalid")
            }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
              <span>{{error}}</span>
              {% endfor %}
            </div>
            {% else %} {{form.email(class="form-control")}} {% endif %}
          </div>
          <div class="form-group mb-3">
            {{ form.first_name.label(class="form-control-label") }} {% if
            form.first_name.errors %} {{ form.first_name(class="form-control
            is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.first_name.errors %}
              <span>{{error}}</span>
              {% endfor %}
            </div>
            {% else %} {{form.first_name(class="form-control")}} {% endif %}
          </div>
          <div class="form-group mb-2">
            {{ form.last_name.label(class="form-control-label") }} {% if
            form.last_name.errors %} {{ form.last_name(class="form-control
            is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.last_name.errors %}
              <span>{{error}}</span>
              {% endfor %}
            </div>
            {% else %} {{form.last_name(class="form-control")}} {% endif %}
          </div>
          <div class="form-group mb-2">
            <label> {{ form.image.label() }} </label> <br />
            {{ form.image(class="form-control-file") }} {% if form.image.errors
            %} {% for error in form.image.errors %}
            <span class="text-danger"> {{ error }} </span>
            {% endfor %} {% endif %}
          </div>
        </fieldset>
        <div class="form-group pb-3 pt-3">
          {{ form.submit(class="btn btn-outline-info")}}
        </div>
      </form>
    </div>
  </div>
</body>
{% endblock content %}

edcgeared/templates/user_posts.html
{% extends "layout.html" %} {% block content %}
<body>
  <h2 class="mb-3">
    Posts by {{ user.first_name }} {{ user.last_name}} ({{ posts.total }})
  </h2>
  {% if posts.items %} {% for post in posts.items %}
  <article class="media content-section article-preview">
    <div class="article-metadata">
      <img
        class="rounded-circle article-author-img"
        src="{{ url_for('static', filename='profile_images/' + post.author.image_file) }}"
      />
      <a
        class="mr-2 article-author"
        href="{{ url_for('users.user_posts', email=post.author.email) }}"
        >{{ post.author.first_name }} {{post.author.last_name }}</a
      >
    </div>
    <div class="media-body">
      <h4>
        <a
          class="article-title"
          href="{{ url_for('posts.post', slug=post.slug) }}"
          >{{ post.title }}</a
        >
      </h4>
      <div class="media container">
        <img
          class="article-img"
          src="{{ url_for('static', filename='post_images/' + post.image) }}"
        />
      </div>
    </div>
    <div class="article-footer">
      <small class="text-muted"
        >{{ post.date_posted.strftime('%Y-%m-%d') }}</small
      >
      <small class="text-muted post-likes">Likes: {{ post.rating }}</small>
    </div>
  </article>
  {% endfor %}
  <div>
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1,
    left_current=1, right_current=2) %} {% if page_num %} {% if posts.page ==
    page_num %}
    <a
      class="btn btn-info mb-2"
      href="{{ url_for('users.user_posts', email=user.email, page=page_num) }}"
      >{{ page_num }}</a
    >
    {% else %}
    <a
      class="btn btn-outline-info mb-2"
      href="{{ url_for('main.index', email=user.email, page=page_num) }}"
      >{{ page_num }}</a
    >
    {% endif %} {% else %} ... {% endif %} {% endfor %}
  </div>
  {% else %}
  <div>
    <article class="media content-section">
      <h4>No posts found</h4s>
    </article>
  </div>
  {%endif%}
</body>
{% endblock content %}